name: RoodGames
version: 1.0
description: R00DGames
author: cooltimmetje
depend: [TitleManager, CharsAPI, HolographicDisplays, Citizens]
main: me.Cooltimmetje.RoodGames.Main
commands:
    setgame:
        description: setgame
    reloadstatues:
        description: reloadstatues
    resetinv:
        description: resetinv
    createbeacon:
        description: createbeacon
    gamelist:
        description: gamelist